### ISSUE TITLE
Pendiente: homogeneizar el separador de las cifras

### ISSUE THREAD

**Issue by benthamite** [tlon-team/babel-refs#1]
A veces usamos el espacio y otras veces, el punto.

**Comment by benthamite** [comment]
@worldsaround, ¿podés fijarte si esto requiere alguna acción o si puede cerrarse? Creo que últimamente usábamos siempre el punto y no el espacio. También se podría actualizar la guía de estilo para aclarar este punto.

**Comment by worldsaround** [comment]
Antes de hacer modificaciones, quiero saber si todavía aceptas ese criterio. El del _Panhispánico_, [_sub voce_ número](https://www.rae.es/dpd/n%C3%BAmeros), 1.1, difiere del "nuestro" en que prescribe el espacio fino en lugar del punto, que considera incorrecto. Me parece que detrás de todo esto está la aceptación del punto como separador de los decimales, además de la coma. Para desambiguar, supongo, casos como 98.647 (que podría significar tanto 98,647 como 98 647) se adopta el espacio. Nosotros, por otro lado, solo escribimos decimales con coma y nunca con punto. Al parecer, estas normas de la RAE se transformaron en las típicas noticias de relleno que se reproducen en muchos medios de comunicación, con titulares como "Haz escrito mal los números toda tu vida", lo cual puede contribuir en algunos casos a que el punto sea visto como un error.

**Comment by benthamite** [comment]
Bueno, tal vez se podría adoptar ese criterio “y listo”. El caracter que debería usarse es *thin non-break space*. Lo agregué al menú de Markdown (aunque todavía no está empujado). ¿Querés hacer los cambios?

**Comment by worldsaround** [comment]
yo me encargo

**Comment by worldsaround** [comment]
> Lo agregué al menú de Markdown

Podés agregar también los puntos suspensivos (…)

**Comment by benthamite** [comment]
Hecho.

**Comment by worldsaround** [comment]
Ahora en el medio de los cambios me doy cuenta que LaTex no respeta esos espacios _thin_ sean o no _non-breaking_. Quiero decir, visualmente no muestra ningún espacio. Tomé la decisión de reemplazar todos los _thin non-breaking spaces_ dentro de fórmulas LaTex por _non-breaking spaces_ normales, al final de los reemplazos. Si se te ocurre una mejor idea, avisame.

**Comment by benthamite** [comment]
Me parece bien. Sugiero que lo tengas presente y si notás algún problema, lo volvemos a discutir.

**Comment by worldsaround** [comment]
Retiro lo dicho. LaTex sí soporta esos espacios. Esto está hecho.

**Comment by benthamite** [comment]
Agrego para referencia futura:

En lugar de *thin space*, debe usarse siempre *narrow non-break space*. El espacio que insertan estos dos caracteres es exactamente el mismo, como acabo de constatar en una prueba (ver imagen al final de este comentario), pero este último tiene la ventaja de que si hay un salto de línea, no se separan las palabras.

Hace un tiempo ya había hecho unos reemplazos pero ahora voy a corroborar que esté todo bien. El comando `tlon-manual-fix-thin-spaces` ahora pasa a llamarse `tlon-manual-fix-narrow-spaces`. (El comando ya insertba un *narrow non-break space* pero el nombre no había quedado actualizado.)
