### ISSUE TITLE
Crear archivo CSL para versiones de audio

### ISSUE THREAD

**Issue by benthamite** [tlon-team/babel-refs#5]
Una ventaja de nuestro sistema de citas es que podemos “customizar” la forma en que el narrador artificial lidia con las obras citadas. En particular, podemos (1) excluir de la narración las notas al pie e incluir solamente las notas marginales y (2) definir un nuevo archivo CSL que genere las citas según cómo queremos que sean leídas. Lo que yo haría entonces sería desarrollar una serie de funciones de Emacs Lisp que exportan a un archivo temporario el archivo de Markdown que queremos “locutar”, borran las notas al pie, reemplazan las llamadas a las notas marginales por la nota misma (para que aparezcan inmediatamente luego del correspondiente texto principal), y reemplazan las claves BibTeX por las citas con el formato especial de CSL.

Lo que necesitaría es que crees este archivo, @worldsaround. Mi impresión es que la forma correcta de narrar una cita es mencionar solo el autor y el título de la obra. Por ejemplo, la primera nota marginal de [este artículo](https://altruismoeficaz.net/articulos/cuanto-deberian-pagar-los-gobiernos-para-prevenir-catastrofes-el-papel-limitado-del-largoplacismo),

> Nick Beckstead (2013) [*On the Overwhelming Importance of Shaping the Far Future*](https://doi.org/10.7282/T35M649T), tesis doctoral, Universidad Rutgers; Nick Bostrom (2013) [Existential risk prevention as global priority](https://doi.org/10.1111/1758-5899.12002), *Global Policy*, vol. 4, pp. 15--31; Hilary Greaves & William MacAskill (2021) [The case for strong longtermism](https://globalprioritiesinstitute.org/hilary-greaves-william-macaskill-the-case-for-strong-longtermism-2/), GPI Working Paper No. 5-2021, Global Priorities Institute, Universidad de Oxford; William MacAskill (2022) [*What We Owe the Future*](https://worldcat.org/search?q=978-1-5416-1862-6), Nueva York: Basic Books; Toby Ord (2020) [*The Precipice: Existential Risk and the Future of Humanity*](https://worldcat.org/search?q=1-5266-0021-8), Londres: Bloomsbury Publishing. Por "largoplacistas" nos referimos a personas especialmente preocupadas por que el futuro a largo plazo de la humanidad vaya bien.

quedaría así:

> Nick Beckstead, On the Overwhelming Importance of Shaping the Far Future; Nick Bostrom, Existential risk prevention as global priority; Hilary Greaves y William MacAskill, The case for strong longtermism; William MacAskill, What We Owe the Future; Toby Ord, The Precipice: Existential Risk and the Future of Humanity. Por “largoplacistas” nos referimos a personas especialmente preocupadas por que el futuro a largo plazo de la humanidad vaya bien.

**Comment by worldsaround** [comment]
Ya lo empujé al repo. Lo probé bastante y funciona perfecto, aunque no es imposible que haya algún caso anómalo que surja con el tiempo y que demuestre que en realidad no estaba libre de errores. Qué herramienta vas a usar para implementar este archivo? Te lo pregunto porque lo probé en citar y en Zotero, y los resultados son diferentes. Creo que citar no hace caso de que lo digan los archivos en "locales" (¿quizá no está seteado correctamente?) y hace caso omiso de la modificación, en el mismo CSL, de las instrucciones que debe tomar por defecto de algún otro lado. En Zotero, en cambio, funciona parcialmente. Esto involucra dos casos:

1) & se mantiene como está (no debería y si se aplican nuestros "locales" no ocurriría). Se puede indicar al modelo que siempre lo lea como "y", si no lo hace por defecto.

2) 'et. al.' se mantiene en citar, pero en Zotero es correctamente reemplazado por la expresión "y otros" (quizá haya alguna otra expresión más adecuada para la lectura).

Una última aclaración. Dejé las comillas simples, porque me parece que ayuda a la interpretación correcta de la lectura automatizada, por ejemplo: Nick Beckstead, ‘On the overwhelming importance of shaping the far future’.

Creo que podemos cerrar esto, pero no dudes en reabrirlo si ves algo que deba ser modificado.

**Comment by benthamite** [comment]
Gracias. Cuando mencionás Zotero, ¿cuál sería concretamente la manera de probar el archivo CSL con ese sitio?

En cualquier caso, aunque no funcione igual con citar, puedo reemplazar fácilmente ‘&’ por ‘y’, y ‘et al’ por ‘y otros’ por lo que esto no debería generar problemas.

**Comment by benthamite** [comment]
¿Cómo maneja los *locators* este archivo de CSL? Debería ignorarlos (dado que no tiene sentido que en una narración el locutor mencione la ubicación precisa de una obra).

**Comment by worldsaround** [comment]
> Gracias. Cuando mencionás Zotero, ¿cuál sería concretamente la manera de probar el archivo CSL con ese sitio?

Me refería al programa Zotero. Ahí en Settings podés agregar los CSLs que quieras.

> ¿Cómo maneja los locators este archivo de CSL? Debería ignorarlos (dado que no tiene sentido que en una narración el locutor mencione la ubicación precisa de una obra).

El archivo lo que hace es reemplazar una clave determinada por la información en stable.bib y la ordena de cierta manera. No se mete con los _locators_ ni con otras porciones de texto que estén en el artículo que hay que _locutar_.  Lo mismo vale para long.csl y short.csl. Me parece que los _locators_ son más bien una _feature_ de Org Cite
